version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: 'src\IP.i4o\DotNetProjects.IndexedLinq.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}
  
configuration: Release

before_build:
  - nuget restore
  
build:
  project: src\IndexedLinq.sln

test_script:
  - cmd: nunit3-console src\IP.i4o.Tests\DotNetProjects.IndexedLinq.Tests.csproj --result=myresults.xml;format=AppVeyor

#artifacts:
#  - path: '**\DotNetProjects.Migrator*.nupkg'

#deploy:
#  provider: NuGet
#  api_key:
#    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
#  artifact: /.*\.nupkg/
  
  
  