version: 1.0.{build}

branches:
  only:
    - master

image: Visual Studio 2017

dotnet_csproj:
  patch: true
  file: 'src\IP.i4o\DotNetProjects.IndexedLinq.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
configuration: Release

before_build:
  - nuget restore src\IndexedLinq.sln
  
build:
  project: src\IndexedLinq.sln

test:
  assemblies:
    only:
      - '**\DotNetProjects.IndexedLinq.Tests.dll'

artifacts:
  - path: '**\DotNetProjects.IndexedLinq*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/